version: 0.2

env:
  secrets-manager:
    TWITCH_CLIENT_ID: ProjectPigeon:TWITCH_CLIENT_ID
    TWITCH_CLIENT_SECRET: ProjectPigeon:TWITCH_CLIENT_SECRET
    MONGO_URI: ProjectPigeon:MONGO_URI

phases:
  install:
    commands:
      - npm i
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
